[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "nginx", "nodejs_22"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install && npm run build"
]

[start]
# 1. Cambiamos 'node' por 'sh' (o eliminamos si tiene permisos de ejecución)
# 2. Corregimos la ruta a ./assets/... (relativa a /app)
cmd = "sh ./assets/scripts/pre-start.sh && php-fpm -D && nginx -g 'daemon off;'"
