[phases.setup]
# Cambiamos php83 por php84
nixPkgs = ["php84", "php84Packages.composer", "nginx", "nodejs_22"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install && npm run build"
]

[start]
cmd = "node /assets/scripts/pre-start.sh && php-fpm -D && nginx -g 'daemon off;'"
